/*
gradlew -Dhttp.proxyHost=proxy.ext.ray.com -Dhttp.proxyPort=80 -Dhttps.proxyHost=proxy.ext.ray.com -Dhttps.proxyPort=80 build cleanEclipse eclipse
*/

plugins {
    id "org.javamodularity.moduleplugin" version "1.8.9"
}
version = "1.0.0"

subprojects {

    apply plugin: 'java-library'
    apply plugin: 'org.javamodularity.moduleplugin'
	apply plugin: 'eclipse'

    group 'com.thomaswilde'
    apply plugin: 'maven-publish'

    repositories {
        mavenCentral()
    }

    dependencies {
        // Use JUnit test framework.
        testImplementation group: 'junit', name: 'junit', version: junit_version
    }

    tasks.register('sourcesJar', Jar) {
        from sourceSets.main.allJava
        archiveClassifier.set('sources')
    }

    tasks.register('javadocJar', Jar) {
        from javadoc
        archiveClassifier.set('javadoc')
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                from components.java
                artifact sourcesJar
                artifact javadocJar

                // Centralized configuration
                repositories {
                    maven {
                      
                    }
                }
            }
        }
    }


    
    eclipse {
    	classpath {
        	downloadJavadoc = true
        	downloadSources = true
    	}
	}



eclipse.classpath.file {
    whenMerged {
    	//entries.each { it.entryAttributes['module'] = 'true' }
        entries.findAll { isModule(it) }.each { it.entryAttributes['module'] = 'true' }
    }
}



}

boolean isModule(entry) {
    // filter java 9 modules
    //true
    entry.kind == 'lib' || entry.kind == 'src'  // Only libraries can be modules
}
