/*
gradlew -Dhttp.proxyHost=proxy.ext.ray.com -Dhttp.proxyPort=80 -Dhttps.proxyHost=proxy.ext.ray.com -Dhttps.proxyPort=80 build cleanEclipse eclipse
*/

plugins {
    id 'base'
}
version = "1.0.0"

subprojects {

    apply plugin: 'java-library'
	apply plugin: 'eclipse'

    group 'com.thomaswilde'
    apply plugin: 'maven-publish'

    repositories {
        mavenCentral()
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        withSourcesJar()
        withJavadocJar()
    }

    sourceSets {
        main {
            java {
                exclude '**/module-info.java'
            }
        }
    }

    tasks.withType(JavaCompile).configureEach {
        exclude '**/module-info.java'
    }

    dependencies {
        // Use JUnit test framework.
        testImplementation group: 'junit', name: 'junit', version: junit_version
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                from components.java

                // Centralized configuration
                repositories {
                    maven {
                      
                    }
                }
            }
        }
    }


    
    eclipse {
    	classpath {
        	downloadJavadoc = true
        	downloadSources = true
    	}
	}
}
