junit_version=4.13.2
commons_io_version=2.15.1
sfl4j_version=2.0.12
poi_version=5.2.5
poi_ooxml_version=5.2.5
poi_scratchpad_version=5.2.5
xmlbeans_version=5.2.0
pdfbox_version=2.0.31
bean_utils_version=1.9.4
poiutil_version=1.1.1
poiutil_artifact=POI-Util
pdfboxutil_version=1.1.1
pdfboxutil_artifact=PDFBox-Util
docparser_version=1.1.1
docparser_artifact=DocParser
